M48
; DRILL file {KiCad 8.0.8} date 2025-07-05T11:35:31-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-05T11:35:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X3.8Y-3.05
X3.8Y-4.95
X6.9Y-3.05
X6.9Y-4.95
T2
X3.5435Y-4.0
X5.0065Y-4.0
X5.6935Y-4.0
X7.1565Y-4.0
T3
X3.175Y-2.975
X3.175Y-5.55
X7.575Y-2.975
X7.575Y-5.55
M30
